program calc_error_norms

!--------------------------------------------------------------------
! This program calculates reads input from file generated by ncl.
! The ngmath subroutine "natgrid" is used to interpolate.
!--------------------------------------------------------------------



implicit none

include 'netcdf.inc'




integer, parameter :: dbl_kind = selected_real_kind(13)



integer :: i
integer :: NPNTS, NUMXOUT, NUMYOUT

integer :: ncid_in,ncid_out,err
integer :: varid
integer :: dimid, xid


real (kind = dbl_kind), allocatable ::                               &
           x2_conv_1d(:), x1_conv_1d(:), h_star_conv_1d(:),  &
           x2_vec(:), x1_vec(:), h_star_conv_interp_1d(:)



! read in array limits
err = NF_OPEN("natgrid_input.nc",NF_NOWRITE,ncid_in)
err = NF_INQ_DIMID(ncid_in,'ncl0',dimid)
err = NF_INQ_DIMLEN(ncid_in,dimid,NPNTS)
err = NF_INQ_DIMID(ncid_in,'x2_h',dimid)
err = NF_INQ_DIMLEN(ncid_in,dimid,NUMYOUT)
err = NF_INQ_DIMID(ncid_in,'x1_h',dimid)
err = NF_INQ_DIMLEN(ncid_in,dimid,NUMXOUT)




print *
print *, "   NPNTS =", NPNTS, "   NUMXOUT =", NUMXOUT, "   NUMYOUT =", NUMYOUT
print *



! read in variables
allocate (x2_conv_1d(NPNTS))
allocate (x1_conv_1d(NPNTS))
allocate (h_star_conv_1d(NPNTS))
allocate (x2_vec(NUMYOUT))
allocate (x1_vec(NUMXOUT))
err = NF_INQ_VARID(ncid_in,'x2_conv_1d',varid)
err = NF_GET_VAR_DOUBLE(ncid_in,varid,x2_conv_1d)
err = NF_INQ_VARID(ncid_in,'x1_conv_1d',varid)
err = NF_GET_VAR_DOUBLE(ncid_in,varid,x1_conv_1d)
err = NF_INQ_VARID(ncid_in,'h_star_conv_1d',varid)
err = NF_GET_VAR_DOUBLE(ncid_in,varid,h_star_conv_1d)
err = NF_INQ_VARID(ncid_in,'x2_vec',varid)
err = NF_GET_VAR_DOUBLE(ncid_in,varid,x2_vec)
err = NF_INQ_VARID(ncid_in,'x1_vec',varid)
err = NF_GET_VAR_DOUBLE(ncid_in,varid,x1_vec)

err = NF_CLOSE(ncid_in)


allocate (h_star_conv_interp_1d(NUMXOUT*NUMYOUT))


! Perform interpolation
print *
print *, "Performing interpolation ...."
call NATGRIDD (NPNTS,x2_conv_1d,x1_conv_1d,h_star_conv_1d,NUMXOUT,NUMYOUT,  &
               x2_vec,x1_vec,h_star_conv_interp_1d,err)
print *, ".... finished interpolation"



! Output interpolated data to file

err = NF_CREATE("natgrid_output.nc", NF_CLOBBER, ncid_out)

err = NF_REDEF(ncid_out)
err = NF_DEF_DIM(ncid_out,'x',NUMXOUT*NUMYOUT,xid)
err = NF_DEF_VAR(ncid_out, 'h_star_conv_interp_1d',NF_DOUBLE,1,xid,varid)
err = NF_ENDDEF(ncid_out)

err = NF_INQ_VARID(ncid_out,'h_star_conv_interp_1d',varid)
err = NF_PUT_VAR_DOUBLE(ncid_out,varid,h_star_conv_interp_1d)

err = NF_CLOSE(ncid_out)




end program calc_error_norms
